ServiceHost = "127.0.0.1"
ServicePort = 8000
Secret = "your_super_secret_key"
ExpiresIn = "15m"  # <-- Уменьшаем время жизни Access Token до 15 минут
RefreshExpiresIn = "720h" # <-- Refresh Token живет 30 дней
Host = "127.0.0.1"
Port = "9000"
User = "minioadmin"     # Стандартный логин MinIO
Pass = "minioadmin"     # Стандартный пароль MinIO
Bucket = "usecase-images" # Имя бакета, куда будем грузить
PublicUrl = "http://127.0.0.1:9000" # URL для доступа из браузера