# Основные настройки (корень)
ServiceHost = "127.0.0.1"
ServicePort = 8000

# Секция для JWT (соответствует полю JWT в структуре Config)
[JWT]
Secret = "your_super_secret_key"
ExpiresIn = "15m"
RefreshExpiresIn = "720h"

# Секция для Minio (соответствует полю Minio в структуре Config)
[Minio]
Host = "127.0.0.1"
Port = "9000"
User = "minioadmin"
Pass = "minioadmin"
Bucket = "usecase-images"
PublicUrl = "http://127.0.0.1:9000"

# Если вы используете Redis из конфига (хотя в коде он брался из ENV, но для порядка можно добавить)
[Redis]
Host = "127.0.0.1"
Port = 6379